### ISSUE TITLE
Enh: add files to ContentAddonActiveRecord such as Comment

### ISSUE THREAD

**Issue by funkycram** [humhub/rest#104]
### Is your feature request related to a problem? Please describe.

Get a Comment ([command](https://marketplace.humhub.com/module/rest/docs/html/comment.html#/paths/~1comment~1%7Bid%7D/get)).

You cannot retrieve attached files

### Describe the solution you'd like

The same way files are attached to Content ([command](https://marketplace.humhub.com/module/rest/docs/html/content.html#tag/Content/paths/~1content~1%7Bid%7D/get)):
![image](https://user-images.githubusercontent.com/23310825/224000261-20e5d20c-ce1a-462a-8aff-f2ff49572f14.png)

**Comment by funkycram** [comment]
Thanks @gevorgmansuryan !
@luke- tested, it works well, I think you can merge this commit.
I'll also add it to the Survey module for files attached to answers.

**Comment by funkycram** [comment]
Perhaps we should add it to the doc also.

**Comment by luke-** [comment]
Yes, we definitly need to add this into the doc

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/rest/pull/109

**Comment by funkycram** [comment]
I've also added the missing `Like` definition to the `Comment` definition.
