### ISSUE TITLE
Refactor Bearer Auth

### ISSUE THREAD

**Issue by luke-** [humhub/rest#105]
Currently, JWT authentication is basically a **Bearer Auth** using a JWT token which contains a user id.
This is a bit of a strange implementation.

We should remove this JWT stuff here and simply create two inputs in the backend:

**Bearer Auth:**
-  API Token (Random String)
- Bearer Auth User (User Picker)

On existing installs to ensure compatibility the JWT Key should become the Bearer API Token, Auth User should be the Admin.

**Comment by luke-** [comment]
Maybe related: https://github.com/humhub/rest/issues/8#issuecomment-1473588038

I'm not sure if I'm missing anything here regarding "JWT".

**Comment by gevorgmansuryan** [comment]
@luke- what if refactor and use CompositeAuth and add JWTAuth to authMethods along with HttpBearerAuth? Also we can support other methods too (HttpBasicAuth and QueryParamAuth)
