### ISSUE TITLE
Space: Membership Attributes

### ISSUE THREAD

**Issue by luke-** [humhub/rest#115]
An Admin should be able to set following additional optional attributes:
- space_membership.show_at_dashboard 
- space_membership.can_cancel_membership

https://marketplace.humhub.com/module/rest/docs/html/space.html#tag/Membership/paths/~1space~1%7Bid%7D~1membership~1%7BuserId%7D/post

**Comment by gevorgmansuryan** [comment]
https://github.com/humhub/humhub/pull/6240
