### ISSUE TITLE
Enable/Disable user and its visibility

### ISSUE THREAD

**Issue by denser** [humhub/rest#146]
### What steps will reproduce the problem?
i.e. running /user/883 PUT request with body
```
{
    "account": {
        "visibility": 0,
        "status": 1
    }
}
```

Want to change visibility and/or status(enable or disable user) and nothing changes. System response wit code 200 and show user data.

### What is the expected result?
status or visibility attribute changes

### What do you get instead?
status or visibility attribute stay as was

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0
| PHP version     | 8.1.2
| Operating system |ubuntu

Only way to allow edit this attributes is add rules in:
```
/protected/humhub/modules/user/models/User.php

[['status', 'visibility'], 'safe'],
```

May be should make it possible out of the box? API must allow edit user visibility and on/off.

**Comment by marc-farre** [comment]
Can you try with the unreleased 0.9.3 version?
You'll see [on the change log](https://github.com/humhub/rest/blob/master/docs/CHANGELOG.md#093-unreleased) that some improvements have been done on the subject.

```sh
git clone https://github.com/humhub/rest.git
```

**Comment by luke-** [comment]
I'm just released 0.9.3. Please test against this version.

**Comment by denser** [comment]
Well done, it works!

**Comment by denser** [comment]
False ok. Now it wont works

**Comment by denser** [comment]
Check my hack and it works with it. Probably while last check it was cached or like that.

**Comment by denser** [comment]
Figure it out. Somewhy changes was rollback for controller...updated via web ui. Now check files. Have to check all of them tho... closing.
