### ISSUE TITLE
Switch to User language on API Requests

### ISSUE THREAD

**Issue by QuentinEcollectivites** [humhub/rest#151]
Hi,

I'm interested in receiving API notifications in French language. Is there a specific configuration module where I can set this preference?

Thank you for your help.

Best regards,

**Comment by QuentinEcollectivites** [comment]
Sure : 
![image](https://github.com/humhub/rest/assets/114567503/4ae8efe6-d9f9-4421-8e12-d4cb9d17594b)
Comments on Humhub interface
![image](https://github.com/humhub/rest/assets/114567503/7d9ca6b0-07f0-4a77-a405-1159dcaceca0)
On return API 

Thx :)

**Comment by gevorgmansuryan** [comment]
hi @QuentinEcollectivites , can you please try to make an API call with `Accept-Language: fr-fr` header ?
