### ISSUE TITLE
Add requirements.php

### ISSUE THREAD

**Issue by marc-farre** [humhub/rest#155]
In anticipation on the new requirements.php support (https://github.com/humhub/humhub/issues/6744), this file could be created on this module regarding the URL Rewriting requirement.

@luke- I can create it if you want.

**Comment by luke-** [comment]
@marc-farre Good point. Yes please create a PR if you like!

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/rest/pull/156
I'm not sure about the wording.

**Comment by luke-** [comment]
@marc-farre Thanks, it's fine.
