### ISSUE TITLE
Query pending invites

### ISSUE THREAD

**Issue by absynth42** [humhub/rest#161]
It would be great if there was a way to query pending invites. For example, the GET verb for /api/v1/user/invite could be used for this. 

The pending invites could then be fed into automation (external CRM etc., or HumHub's own automation) to remind those users to complete registration. 

The /api/v1/user GET verb currently does not output invitations, only users who have completed registration.

**Comment by luke-** [comment]
Available with Rest module release 0.10.0

**Comment by absynth42** [comment]
Great, thanks! 

This kind of paves the road for enhanced user onboarding workflows: 
- User gets invited by admin
- User gets a reminder e-mail to complete onboarding if they didn't click on invite link for X days
- Unanswered invitation is escalated to customer success manager (or deleted) after Y days

With the API endpoints, I can implement all this in a third-party tool (like a CRM, or Zapier-like tooling). 

However, the current implementation is missing something like an inviteTimestamp property. It exists in the web UI, so it's likely in the database. 
The GET /user verb doesn't return a "userCreated" property (or similar) either, as far as I can tell.

Therefore, a possible enhancement could be to include the invite date (and while you're at it, the invite source) to the REST array.

**Comment by luke-** [comment]
@gevorgmansuryan Can you please look at this again and add such meta infos if missing?

I expect the `/user` endpoint should also return such information like `created_at/by` and `updated_at/by` in the account.

**Comment by gevorgmansuryan** [comment]
@luke- 
![image](https://github.com/user-attachments/assets/ba669ef1-86af-4a84-a9b2-e8b85e17d30d)
