### ISSUE TITLE
Invite users

### ISSUE THREAD

**Issue by TheMcSebi** [humhub/rest#47]
Hello, I can't find out how to use the invite api. The documentation at https://www.humhub.com/en/marketplace/rest/docs/html/user.html#tag/Invite doesn't help.

**Comment by luke-** [comment]
Currently, the Invite endpoints are not yet implemented.

**Comment by donni106** [comment]
Is it planned to be implemented soon?

**Comment by introspectionism** [comment]
It would be great to get the Invite endpoint implemented! Are there any news about this part of the API?

**Comment by marc-farre** [comment]
@luke- what do you think about this PR https://github.com/humhub/rest/pull/138 ?

Doc:
![image](https://github.com/humhub/rest/assets/23310825/33abf9f5-1d9a-44cb-909d-0372ca5dff3b)

Curl example:
```sh
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer xxxxxxxxxxxxx' -X POST https://my-humhub.com/api/v1/user/invite -d '{"emails":"example1@email.com,example2@email.com"}'
```

**Comment by luke-** [comment]
@marc-farre Thanks!

**Comment by TheMcSebi** [comment]
Amazing, thanks for sharing your work!
