### ISSUE TITLE
Wrong date/time formats on create a task

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/rest#60]
Issue is detected here https://community.humhub.com/s/module-development/?contentId=239935

Cannot create a task with date/time format documented here https://www.humhub.com/en/marketplace/rest/docs/html/task.html#tag/Task:

```
"start_date": "2019-03-23",
"start_time": "10:00",
"end_date": "2019-03-25",
"end_time": "20:30",
```

After investigation we detected only the following formats are possible:

```
"start_date": "2021-05-03 01:02:03",
"start_time": "10:00 AM",
"end_date": "2021-05-04 04:05:06",
"end_time": "7:30 PM",
```

A task will be stored in DB with columns `start_datetime = ‘2021-05-03 01:02:03‘` and `end_datetime = ‘2021-05-04 04:05:06‘`, so the values from time fields will be just ignored.

**Comment by yurabakhtin** [comment]
@luke- I have fixed this in PR https://github.com/humhub/tasks/pull/152 but please note it will works only for `develop` branch of the `rest` module because only there we moved endpoints of external modules. If we need to fix this in the `master` branch I can do the same changes there, let me know.

Also small code cleanup was done in the rest PR https://github.com/humhub/rest/pull/61, it doesn't fix the issue but there old/moved controller `humhub\modules\rest\controllers\task\TaskController` was used, so we need this to avoid errors for case when a Task is created/updated without "Scheduling" fields.

**Comment by luke-** [comment]
@yurabakhtin Thanks, I think that is enough. Can you let the community user know that he can use the develop/beta rest module?

**Comment by yurabakhtin** [comment]
@luke- I have replied there.
