### ISSUE TITLE
API endpoints return 404 Not Found

### ISSUE THREAD

**Issue by trungdang97** [humhub/rest#65]
Shouldn't the API return 403 on Unauthorized GET? I tried to debug the onBeforeRequest() but it doesn't trigger when I send the REST request, only on polling. Even with BasicAuth in Postman, I still got 404 Not Found.

I am using Humhub 1.8.2. And this is the first time I use REST module in Humhub.

How can I resolve this and use the RestAPI?

![image](https://user-images.githubusercontent.com/35669562/126586160-490f63a7-9eb1-4bab-92ea-6929a3cd7807.png)

**Comment by luke-** [comment]
@trungdang97 Did you enabled PrettyUrls? Is any endpoint working? Is the REST Module activated and configured?

**Comment by trungdang97** [comment]
Oh the PrettyUrls config, I commented them out together with Live because I haven't figure out how to setup SSL for socket.io in Humhub Push Service so I change to FCM.

Thank you so much. The API is running fine now.
