### ISSUE TITLE
Is there a way for insert comment on existed post ?

### ISSUE THREAD

**Issue by meowent** [humhub/rest#87]
Is there a way for insert comment on existed post  ?

1. In comment API
https://www.humhub.com/en/marketplace/rest/docs/html/comment.html
Do we have any available Function for adding comments ?

2. In Update post  API
https://www.humhub.com/en/marketplace/rest/docs/html/post.html#/paths/~1post~1{id}/put
What's the content format we should give to for updating ?

3.Is there any other way for putting a comment

**Comment by luke-** [comment]
There is no endpoint for comment creation yet.
See https://github.com/humhub/rest/issues/41
