### ISSUE TITLE
Add a updated_at metadata field 

### ISSUE THREAD

**Issue by srosset81** [humhub/rest#95]
I'm using HumHub Rest API to synchronize data with another semantic database ([code](https://dev.semapps.org/docs/middleware/importer/humhub)).

I'm doing this operation every night.

The problem is that there is no `updated_at` metadata field in the API results (on any of the resources, or so it seems), so I cannot know if a data has been updated or not since the previous synchronization. I thus have to update all the data, which is a waste of time.

Would you consider adding such a field in addition to the existing `created_at` field ?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/rest/pull/98: I added new fields `updated_by` and `updated_at`.
